apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ephemeral-namespace-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ephemeral-namespace-operator
    app.kubernetes.io/part-of: ephemeral-namespace-operator
  name: ephemeral-namespace-operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ephemeral-namespace-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ephemeral-namespace-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-devprod-tenant/ephemeral-namespace-operator/ephemeral-namespace-operator@sha256:cba7a91ebca9decac59e934091455141c69b7201706d4b86c3736d85a2ce6a33
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
