apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ephemeral-namespace-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ephemeral-namespace-operator
    app.kubernetes.io/part-of: ephemeral-namespace-operator
  name: ephemeral-namespace-operator
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ephemeral-namespace-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ephemeral-namespace-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-devprod-tenant/ephemeral-namespace-operator/ephemeral-namespace-operator@sha256:d6df3397e4c627d7d5f7e999a02e0bd303d9a29414f9ed59cfebf8b94ff9dfd7
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
