apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ephemeral-namespace-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-devprod-tenant/ephemeral-namespace-operator/ephemeral-namespace-operator@sha256:33cb0db106383410683ed573da9f1a3d05d95e05a684a2c4f88168207f2a4d91
        name: container-image
        resources: {}
status: {}
