apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ephemeral-namespace-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-devprod-tenant/ephemeral-namespace-operator/ephemeral-namespace-operator@sha256:6025a32342d71926aca0a103c716a8e4db02a8199af18a198140e279e5e6f789
        name: container-image
        resources: {}
status: {}
